# permissions for end users to edit solutions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: solution-editor-role
rules:
- apiGroups:
  - app.example.com
  resources:
  - solutions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.example.com
  resources:
  - solutions/status
  verbs:
  - get
